"""Generate js/zones.js from tools/reference/zone1970.tab (public domain).

Coordinates column is ISO 6709: +-DD[MM[SS]]+-DDD[MM[SS]].
Run once from the repo root: python tools/gen_zones.py
"""
import re

def dms(sign, digits, deg_width):
    d = int(digits[:deg_width]); rest = digits[deg_width:]
    m = int(rest[:2]) if len(rest) >= 2 else 0
    s = int(rest[2:4]) if len(rest) >= 4 else 0
    v = d + m / 60.0 + s / 3600.0
    return -v if sign == "-" else v

entries = []
with open("tools/reference/zone1970.tab", encoding="utf-8") as f:
    for line in f:
        if line.startswith("#") or not line.strip():
            continue
        cols = line.rstrip("\n").split("\t")
        coord, zone = cols[1], cols[2]
        m = re.match(r"([+-])(\d{4}|\d{6})([+-])(\d{5}|\d{7})$", coord)
        if not m:
            raise SystemExit("unparseable coord %r for %s" % (coord, zone))
        lat = dms(m.group(1), m.group(2), 2)
        lon = dms(m.group(3), m.group(4), 3)
        entries.append((zone, lat, lon))

entries.sort()
lines = ['"%s":[%.2f,%.2f]' % e for e in entries]
js = ("// GENERATED by tools/gen_zones.py from zone1970.tab (public domain tzdb).\n"
      "// Do not edit by hand; re-run the generator instead.\n"
      "window.WC = window.WC || {};\n"
      "WC.ZONES = {" + ",".join(lines) + "};\n")
with open("js/zones.js", "w", encoding="utf-8", newline="\n") as f:
    f.write(js)
print("wrote js/zones.js with %d zones" % len(entries))
