"""Generate js/mapdata.js from tools/reference/land-110m.json.

land-110m.json is TopoJSON from the world-atlas package, derived from
Natural Earth (public domain). Projection: equirectangular onto a
1000x500 viewBox; x=(lon+180)/360*1000, y=(90-lat)/180*500.
Run once from the repo root: python tools/gen_map.py
"""
import json

W, H = 1000.0, 500.0

with open("tools/reference/land-110m.json", encoding="utf-8") as f:
    topo = json.load(f)

sx, sy = topo["transform"]["scale"]
tx, ty = topo["transform"]["translate"]

arcs = []
for arc in topo["arcs"]:
    x = y = 0
    pts = []
    for dx, dy in arc:
        x += dx; y += dy
        pts.append((x * sx + tx, y * sy + ty))  # (lon, lat)
    arcs.append(pts)

def ring(indexes):
    out = []
    for i in indexes:
        pts = arcs[i] if i >= 0 else list(reversed(arcs[~i]))
        if out:
            pts = pts[1:]  # shared endpoint
        out.extend(pts)
    return out

def proj(lon, lat):
    return ((lon + 180.0) / 360.0 * W, (90.0 - lat) / 180.0 * H)

cmds = []
land = topo["objects"]["land"]
if land["type"] == "GeometryCollection":
    land = land["geometries"][0]
assert land["type"] == "MultiPolygon"
for polygon in land["arcs"]:
    for r in polygon:
        coords = ring(r)
        seg = []
        for j, (lon, lat) in enumerate(coords):
            x, y = proj(lon, lat)
            seg.append(("M" if j == 0 else "L") + "%.1f %.1f" % (x, y))
        cmds.append("".join(seg) + "Z")

d = "".join(cmds)
js = ("// GENERATED by tools/gen_map.py from Natural Earth land-110m (public domain).\n"
      "// Do not edit by hand; re-run the generator instead.\n"
      "window.WC = window.WC || {};\n"
      'WC.MAP_PATH = "%s";\n' % d)
with open("js/mapdata.js", "w", encoding="utf-8", newline="\n") as f:
    f.write(js)
print("wrote js/mapdata.js (%d KB, %d rings)" % (len(js) // 1024, len(cmds)))
